name: CI
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
  build-and-publish-sonatype-portal-mock:
    name: 'Build and publish Sonatype Portal Mock'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Sonatype Portal Mock docker image
        uses: ./.github/actions/build
        with:
          gradle-task: ':sonatype-portal-mock:bootBuildImage --imageName ghcr.io/${{ github.repository_owner }}/sonatype-portal-mock:latest'
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/sonatype-portal-mock:latest
  integration-test:
    name: 'Integration test'
    runs-on: 'ubuntu-latest'
    needs:
      - build
      - build-and-publish-sonatype-portal-mock
    services:
      sonatype-portal-mock:
        image: ghcr.io/${{ github.repository_owner }}/sonatype-portal-mock:latest
        ports:
          - 8080:8080
        env:
          SERVER_PORT: '8080'
          PORTALMOCK_TOKEN_NAME: 'mrsmith'
          PORTALMOCK_TOKEN_VALUE: 'morpheus'
          PORTALMOCK_DEPLOYMENT_DELAY_BETWEEN_STEPS: '10s'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Integration test
        uses: ./.github/actions/integration-test
        with:
          sonatype-portal-mock-host: 'sonatype-portal-mock'
          sonatype-portal-mock-port: '8080'
          token-name: 'mrsmith'
          token: 'morpheus'
